# Generated by Django 3.2.13 on 2022-04-29 03:09

import common.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_beat", "0015_edit_solarschedule_events_choices"),
    ]

    operations = [
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project_name",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        null=True,
                        verbose_name="项目名",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="项目入口包名称"
                    ),
                ),
                (
                    "main",
                    models.CharField(
                        default="deploy.yaml", max_length=20, verbose_name="入口文件"
                    ),
                ),
                (
                    "describe",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="描述"
                    ),
                ),
                ("run_num", models.IntegerField(default=0, verbose_name="运行次数")),
            ],
            options={
                "verbose_name": "仓库中心",
                "verbose_name_plural": "仓库中心",
                "db_table": "pgo_iac_repository",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("playbook", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "inventory",
                    models.TextField(blank=True, null=True, verbose_name="主机列表"),
                ),
                ("envvars", models.JSONField(blank=True, null=True, verbose_name="变量")),
                (
                    "extravars",
                    models.JSONField(blank=True, null=True, verbose_name="环境变量"),
                ),
                (
                    "forks",
                    models.IntegerField(blank=True, default=1, verbose_name="并发数"),
                ),
                ("timeout", models.IntegerField(default=3600, verbose_name="超时时间")),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="执行的角色列表"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="执行的tag"
                    ),
                ),
                (
                    "skip_tags",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="跳过的 tag"
                    ),
                ),
                ("alert", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="执行任务名"
                    ),
                ),
                (
                    "celery_id",
                    models.CharField(
                        blank=True, max_length=36, null=True, verbose_name="celery_id"
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "PENDING"),
                            (1, "RUNNING"),
                            (2, "COMPLETED"),
                            (3, "FAILED"),
                            (4, "CANCELED"),
                            (5, "TIMEOUT"),
                        ],
                        default=0,
                        verbose_name="任务执行状态",
                    ),
                ),
                (
                    "output",
                    models.TextField(blank=True, null=True, verbose_name="任务输出"),
                ),
                (
                    "describe",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="描述"
                    ),
                ),
            ],
            options={
                "verbose_name": "仓库中心",
                "verbose_name_plural": "仓库中心",
                "db_table": "pgo_iac_task",
            },
            bases=(common.models.BroadcastModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TaskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[
                            (0, "ok"),
                            (1, "failed"),
                            (2, "skipped"),
                            (3, "unreachable"),
                        ]
                    ),
                ),
                ("play", models.CharField(max_length=512)),
                ("task", models.CharField(max_length=512)),
                ("host", models.CharField(max_length=512)),
                ("ip", models.GenericIPAddressField(null=True)),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("duration", models.FloatField()),
                ("changed", models.BooleanField()),
                ("detail", models.JSONField()),
            ],
            options={
                "verbose_name": "任务事件",
                "verbose_name_plural": "任务事件",
                "db_table": "pgo_iac_task_event",
            },
        ),
        migrations.CreateModel(
            name="TaskStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("host", models.CharField(max_length=512)),
                ("ip", models.GenericIPAddressField(null=True)),
                ("ok", models.IntegerField(default=0)),
                ("changed", models.IntegerField(default=0)),
                ("dark", models.IntegerField(default=0)),
                ("failures", models.IntegerField(default=0)),
                ("ignored", models.IntegerField(default=0)),
                ("rescued", models.IntegerField(default=0)),
                ("skipped", models.IntegerField(default=0)),
                (
                    "task_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="pgo_iac.task"
                    ),
                ),
            ],
            options={
                "verbose_name": "任务状态概览",
                "verbose_name_plural": "任务状态概览",
                "db_table": "pgo_iac_task_stats",
            },
        ),
        migrations.CreateModel(
            name="TaskPeriodic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("playbook", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "inventory",
                    models.TextField(blank=True, null=True, verbose_name="主机列表"),
                ),
                ("envvars", models.JSONField(blank=True, null=True, verbose_name="变量")),
                (
                    "extravars",
                    models.JSONField(blank=True, null=True, verbose_name="环境变量"),
                ),
                (
                    "forks",
                    models.IntegerField(blank=True, default=1, verbose_name="并发数"),
                ),
                ("timeout", models.IntegerField(default=3600, verbose_name="超时时间")),
                (
                    "role",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="执行的角色列表"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="执行的tag"
                    ),
                ),
                (
                    "skip_tags",
                    models.CharField(
                        blank=True, max_length=30, null=True, verbose_name="跳过的 tag"
                    ),
                ),
                ("alert", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=200)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "describe",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="描述"
                    ),
                ),
                (
                    "beat",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
            options={
                "verbose_name": "周期性任务",
                "verbose_name_plural": "周期性任务",
                "db_table": "pgo_iac_task_periodic",
            },
        ),
    ]
