# Generated by Django 3.2.13 on 2022-04-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='icon',
            field=models.ImageField(blank=True, default='icon/user/2022/04/17/pgoops.png', null=True, upload_to='icon/user/%Y/%m/%d/'),
        ),
    ]
