# Generated by Django 3.2.13 on 2022-05-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pgo_data_map", "0004_alter_classify_icon"),
        ("pgo_message_center", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrometheusApplicationGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=32)),
                (
                    "scheme",
                    models.IntegerField(choices=[(0, "http"), (1, "https")], default=0),
                ),
                ("metrics_path", models.CharField(max_length=64)),
                ("consul_tag", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "应用分组",
                "verbose_name_plural": "应用分组",
                "db_table": "pgo_monitor_application_group",
            },
        ),
        migrations.CreateModel(
            name="PrometheusRules",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("name", models.CharField(max_length=128)),
                ("promeql", models.CharField(blank=True, max_length=1024, null=True)),
                (
                    "condition",
                    models.IntegerField(
                        choices=[
                            (0, "=="),
                            (1, "!="),
                            (2, ">"),
                            (3, ">="),
                            (4, "<"),
                            (5, "<="),
                        ],
                        default=0,
                    ),
                ),
                ("threshold_value", models.IntegerField(blank=True, null=True)),
                ("duration", models.IntegerField(blank=True, null=True)),
                ("summary", models.CharField(blank=True, max_length=1024, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
                ("extend_labels", models.JSONField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pgo_monitor.prometheusapplicationgroup",
                    ),
                ),
                (
                    "severity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pgo_message_center.level",
                    ),
                ),
            ],
            options={
                "verbose_name": "告警规则",
                "verbose_name_plural": "告警规则",
                "db_table": "pgo_monitor_prometheus_rules",
            },
        ),
        migrations.CreateModel(
            name="PrometheusNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("config_path", models.CharField(max_length=128)),
                ("rules_path", models.CharField(max_length=128)),
                ("port", models.CharField(max_length=32)),
                ("status", models.BooleanField(default=True)),
                ("master", models.BooleanField(default=False)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pgo_data_map.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "服务器组",
                "verbose_name_plural": "服务器组",
                "db_table": "pgo_monitor_prometheus_node",
            },
        ),
        migrations.CreateModel(
            name="PrometheusApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "port",
                    models.IntegerField(choices=[(0, "http"), (1, "https")], default=0),
                ),
                ("scheme", models.IntegerField()),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pgo_data_map.asset",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pgo_monitor.prometheusapplicationgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
