# Generated by Django 3.2.13 on 2022-05-09 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pgo_data_map", "0004_alter_classify_icon"),
        ("pgo_message_center", "0002_initial"),
        ("pgo_monitor", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PrometheusApplication",
            new_name="Application",
        ),
        migrations.RenameModel(
            old_name="PrometheusApplicationGroup",
            new_name="Group",
        ),
        migrations.RenameModel(
            old_name="PrometheusNode",
            new_name="Node",
        ),
        migrations.RenameModel(
            old_name="PrometheusRules",
            new_name="Rules",
        ),
        migrations.AlterModelOptions(
            name="application",
            options={"verbose_name": "应用分组", "verbose_name_plural": "应用分组"},
        ),
        migrations.AlterModelTable(
            name="application",
            table="pgo_monitor_application",
        ),
        migrations.AlterModelTable(
            name="group",
            table="pgo_monitor_group",
        ),
        migrations.AlterModelTable(
            name="node",
            table="pgo_monitor_node",
        ),
        migrations.AlterModelTable(
            name="rules",
            table="pgo_monitor_rules",
        ),
    ]
