# Generated by Django 3.2.13 on 2022-05-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pgo_monitor", "0002_auto_20220509_1729"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="port",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="application",
            name="scheme",
            field=models.IntegerField(choices=[(0, "http"), (1, "https")], default=0),
        ),
    ]
