# Generated by Django 3.2.13 on 2022-05-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pgo_monitor", "0003_auto_20220509_1734"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="grafana_path",
            field=models.CharField(default="", max_length=280),
        ),
    ]
