# Generated by Django 3.2.13 on 2022-05-18 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pgo_monitor", "0007_application_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="application",
                to="pgo_monitor.group",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="port",
            field=models.IntegerField(),
        ),
    ]
