# Generated by Django 3.2.13 on 2022-05-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pgo_data_map", "0004_alter_classify_icon"),
        ("pgo_monitor", "0008_auto_20220518_1656"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="pgo_data_map.asset"
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="host",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="pgo_data_map.asset"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="application",
            unique_together={("group", "asset")},
        ),
        migrations.CreateModel(
            name="LinkClassify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "classify",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitor_link_classify",
                        to="pgo_data_map.classify",
                    ),
                ),
            ],
            options={
                "verbose_name": "节点关联CMDB类型",
                "verbose_name_plural": "节点关联CMDB类型",
                "db_table": "pgo_monitor_link_classify",
            },
        ),
    ]
