# Generated by Django 3.2.13 on 2022-05-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pgo_data_map", "0004_alter_classify_icon"),
        ("pgo_monitor", "0009_auto_20220520_0050"),
    ]

    operations = [
        migrations.AlterField(
            model_name="node",
            name="config_path",
            field=models.CharField(max_length=128, verbose_name="配置文件路径"),
        ),
        migrations.AlterField(
            model_name="node",
            name="host",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="pgo_data_map.asset",
                verbose_name="绑定主机",
            ),
        ),
        migrations.AlterField(
            model_name="node",
            name="rules_path",
            field=models.CharField(max_length=128, verbose_name="规则文件路径"),
        ),
    ]
