# Generated by Django 3.2.13 on 2022-05-16 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pgo_data_map", "0004_alter_classify_icon"),
        ("pgo_service_tree", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodelinkasset",
            name="asset",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="link_asset",
                to="pgo_data_map.asset",
            ),
        ),
    ]
