# Generated by Django 3.2.13 on 2022-05-16 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pgo_service_tree", "0003_alter_nodelinkasset_asset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nodelinkasset",
            name="node_link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="pgo_service_tree.nodelinkclassify",
                verbose_name="关联表",
            ),
        ),
    ]
