# Generated by Django 3.2.13 on 2022-04-29 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pgo_data_map', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fields',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fields',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classifybind',
            name='child_classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='pgo_data_map.classify', verbose_name='子表ID'),
        ),
        migrations.AddField(
            model_name='classifybind',
            name='parent_classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='pgo_data_map.classify', verbose_name='主表ID'),
        ),
        migrations.AddField(
            model_name='classify',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classify',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pgo_data_map.classify', verbose_name='父Id'),
        ),
        migrations.AddField(
            model_name='classify',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerecord',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='record', to='pgo_data_map.asset', verbose_name='关联资产数据'),
        ),
        migrations.AddField(
            model_name='changerecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetbind',
            name='child_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='pgo_data_map.asset', verbose_name='主记录ID'),
        ),
        migrations.AddField(
            model_name='assetbind',
            name='classify_bind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgo_data_map.classifybind', verbose_name='表关系'),
        ),
        migrations.AddField(
            model_name='assetbind',
            name='parent_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='pgo_data_map.asset', verbose_name='主记录ID'),
        ),
        migrations.AddField(
            model_name='asset',
            name='classify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgo_data_map.classify', verbose_name='关联Classify'),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='classifybind',
            unique_together={('parent_classify', 'child_classify')},
        ),
        migrations.AlterUniqueTogether(
            name='assetbind',
            unique_together={('parent_asset', 'child_asset')},
        ),
    ]
